# File: podman-compose.yaml

services:
    # 1. PHP-FPM Application Service
    app:
        container_name: hafalan-app
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
            - /var/www/html/node_modules
            - /var/www/html/public/build
        env_file:
            - .env.production
        command: php-fpm
        networks:
            - internal

    # 2. Web Server (Nginx) Service with Traefik
    web:
        container_name: hafalan-web
        image: nginx:stable-alpine
        restart: always
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/html:ro
            - /var/www/html/storage
            - /var/www/html/bootstrap/cache
        depends_on:
            - app
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-proxy

            - traefik.http.routers.hafalan.rule=Host(`hafalan.humahub.my.id`)
            - traefik.http.routers.hafalan.entrypoints=websecure
            - traefik.http.routers.hafalan.tls=true
            - traefik.http.routers.hafalan.tls.certresolver=cf
            - traefik.http.services.hafalan.loadbalancer.server.port=80
            - traefik.http.routers.hafalan.middlewares=hafalan-secure,hafalan-cache
            - traefik.http.middlewares.hafalan-secure.headers.stsSeconds=31536000
            - traefik.http.middlewares.hafalan-secure.headers.stsIncludeSubdomains=true
            - traefik.http.middlewares.hafalan-secure.headers.stsPreload=true
            - traefik.http.middlewares.hafalan-secure.headers.frameDeny=true
            - traefik.http.middlewares.hafalan-secure.headers.contentTypeNosniff=true
            - traefik.http.middlewares.hafalan-secure.headers.referrerPolicy=no-referrer-when-downgrade
            - traefik.http.middlewares.hafalan-secure.headers.permissionsPolicy=geolocation=(), microphone=(), camera=()
            - traefik.http.middlewares.hafalan-cache.headers.customResponseHeaders.Cache-Control=public, max-age=3600, immutable
        networks:
            # GANTI 'traefik_web' dengan nama network eksternal Traefik Anda
            - traefik-proxy
            - internal

    # 3. Database Service (PostgreSQL)
    # --- PERUBAHAN DI BAWAH INI ---
    db:
        container_name: hafalan-db-postgres
        image: postgres:15-alpine # Menggunakan image resmi PostgreSQL
        restart: always
        env_file:
            - .env.production
        volumes:
            # PostgreSQL menyimpan data di /var/lib/postgresql/data
            - db_data:/var/lib/postgresql/data
        networks:
            - internal
    # --- AKHIR PERUBAHAN ---

volumes:
    db_data: # Volume ini sekarang akan digunakan oleh PostgreSQL

networks:
    internal:
        driver: bridge
    traefik-proxy:
        external: true
