# File: podman-compose.yaml

services:
    # 1. PHP-FPM Application Service
    app:
        container_name: hafalan-app
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
            - /var/www/html/node_modules
            - ./public/build:/var/www/html/public/build
        env_file:
            - .env
        command: php-fpm
        networks:
            - internal
        # volumes:
        #     - app_storage:/var/www/html/storage

    # 2. Web Server (Nginx) Service with Traefik
    web:
        container_name: hafalan-web
        image: nginx:stable-alpine
        restart: always
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/html:ro
            # - /var/www/html/storage
            # - /var/www/html/bootstrap/cache
            - ./public/build:/var/www/html/public/build:ro
        depends_on:
            - app
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-proxy

            - traefik.http.routers.hafalan.rule=Host(`hafalan.humahub.my.id`)
            - traefik.http.routers.hafalan.entrypoints=websecure
            - traefik.http.routers.hafalan.tls=true
            - traefik.http.routers.hafalan.tls.certresolver=cf
            - traefik.http.routers.hafalan.service=hafalan-service

            # Build assets get longer cache
            - traefik.http.routers.hafalan-assets.rule=Host(`hafalan.humahub.my.id`) && PathPrefix(`/build/`)
            - traefik.http.routers.hafalan-assets.entrypoints=websecure
            - traefik.http.routers.hafalan-assets.tls=true
            - traefik.http.routers.hafalan-assets.tls.certresolver=cf
            - traefik.http.routers.hafalan-assets.service=hafalan-service
            - traefik.http.routers.hafalan-assets.middlewares=hafalan-assets-cache

            # Single service for both routers
            - traefik.http.services.hafalan-service.loadbalancer.server.port=80
            - traefik.http.middlewares.hafalan-assets-cache.headers.customResponseHeaders.Cache-Control=public, max-age=31536000, immutable
        networks:
            # GANTI 'traefik_web' dengan nama network eksternal Traefik Anda
            - traefik-proxy
            - internal

    # 3. Database Service (PostgreSQL)
    # --- PERUBAHAN DI BAWAH INI ---
    db:
        container_name: hafalan-db-postgres
        image: postgres:15
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - internal

volumes:
    db_data: # Volume ini sekarang akan digunakan oleh PostgreSQL
    app_storage:

networks:
    internal:
        driver: bridge
    traefik-proxy:
        external: true
